<a href="https://colab.research.google.com/github/wikmor/deep-neural-networks/blob/main/lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Wstęp
Pierwsze laboratorium dotyczy wprowadzenia do środowiska PyTorch. Z uwagi na fakt, że przygotowanie środowiska może zająć dłuższą chwilę, część ta jest opisana na końcu niniejszej instrukcji i należy ją wykonać w domu (sekcja [Zadanie domowe](#homework)). Ćwiczenie to nie podlega ocenie, natomiast sugerowane jest wykonanie wszystkich poleceń w celu zapoznania się z podstawami operacji na tensorach. Przed przystąpieniem do realizacji zadań należy wykonać następujące kroki:


1.   Uruchomić [Dysk Google](https://drive.google.com/).
2.   Przesłać na [Dysk Google](https://drive.google.com/) plik **lab01.ipynb**.
3.   Kliknąć prawym przyciskiem myszy na plik **lab01.ipynb** na Dysku Google i wybrać opcję **Otwórz za pomocą** a następnie **Google Colaboratory**. <br/>
![colab.png](https://drive.google.com/uc?id=1XzvyggTWZ9j_1I3EegeXK1fu2uBAUSZi)
4.   W menu **Google Colab** wybrać opcję **Runtime**, a następnie **Change runtime type**. <br/>
![runtime_type.png](https://drive.google.com/uc?id=1Ldp2Je0eFZEUTyGxG3xWoYluq1jCv734)
5.   Z rozwijanej listy **Hardware accelerator** wybrać **GPU** a następnie **SAVE**. <br/>
![runtime_gpu.png](https://drive.google.com/uc?id=10IY3WEJJ8UVyVHhPkOgZkR6XlPakV5V5)
6.   Na końcu należy wybrać opcję **Connect**. <br/>
![runtime_gpu.png](https://drive.google.com/uc?id=1juOcGKNVqNJRpoKOg-KCNns15YVHI0vC) <br/>
Gdy przycisk **Connect** zamieni się w status widoczny na poniższym obrazku, można rozpocząć pracę. <br/>
![runtime_gpu.png](https://drive.google.com/uc?id=1w_ERPHdqD0-_fXBnI6zZR9rTPRujA3c4)




# Tensory
Tensory są strukturami danych, które są bardzo podobne do tablic i macierzy. W środowisku **PyTorch** tensory są wykorzystywane do zapisywania danych wejściowych i wyjściowych modelu, jak również jego parametrów. Tensory są podobne do tablic **NumPy**, z tą różnicą, że tensory mogą być uruchamiane na kartach graficznych  lub innym wyspecjalizowanym sprzęcie w celu przyspieszenia obliczeń. Przed rozpoczęciem prac należy zaimportować bibliotekę **PyTorch**. Dla przedstawienia pewnych analogii zaimportowana będzie również biblioteka **NumPy**.

Ustaw kursor na polu z kodem poniżej i wciśnij przycisk image.png

In [2]:
import torch # biblioteka PyTorch
import numpy as np # biblioteka NumPy

## Inicjalizacja tensora
Tensory mogą być inicjalizowane na wiele różnych sposobów. Przykładowo:
### Bezpośrednio z listy
Tensory mogą być tworzone bezpośrednio z listy. Typ danych jest określany automatycznie.


In [3]:
data_list = [[2,5],[3,6],[4,7]] # lista list z elementami w postaci liczb całkowitych
data_tensor = torch.tensor(data_list) # utworzenie tensora z listy
data_tensor

tensor([[2, 5],
        [3, 6],
        [4, 7]])

Utworzony tensor reprezentuje macierz o wymiarach 3x2:

$\begin{bmatrix}
2 & 5 \\
3 & 6 \\
4 & 7
\end{bmatrix}$

Wymiar tensora można sprawdzić następująco:


In [4]:
data_tensor.shape # kształt tensora

torch.Size([3, 2])

Do elementów **shape** odwołujemy się jak w przypadku listy:

In [5]:
data_tensor.shape[0]

3

In [6]:
data_tensor.shape[1]

2

### Z tablicy NumPy
Tensory można również tworzyć z tablicy NumPy

In [7]:
numpy_array = np.array(data_list) # tablica NumPy utworzona z listy
data_tensor = torch.from_numpy(numpy_array) # tensor utworzony z tablicy NumPy
data_tensor

tensor([[2, 5],
        [3, 6],
        [4, 7]])

Tensor można również skonwertować do tablicy NumPy

In [8]:
np_arr = data_tensor.numpy() # tablica NumPy utworzona z tensora
np_arr

array([[2, 5],
       [3, 6],
       [4, 7]])

---
**ZADANIE 1**

Uzupełnij kod poniżej, by zmienna **my_tensor** była tensorem reprezentującym następującą macierz:

$\begin{bmatrix}
2 & 4 & 6\\
1 & 3 & 5 \\
\end{bmatrix}$

In [9]:
my_tensor = torch.tensor([[2, 4, 6], [1, 3, 5]])
my_tensor

tensor([[2, 4, 6],
        [1, 3, 5]])

---
### Z innego tensora
Domyślnie nowy tensor zachowuje wszystkie właściwości (kształt, typ danych) tensora przekazanego jako argument. Można nadpisać pewne właściwości podczas tworzenia.

In [10]:
tensor_2 = torch.ones_like(data_tensor) # tworzenie tensora o wymiarze data_tensor wypełnionego wartościami 1
tensor_2

tensor([[1, 1],
        [1, 1],
        [1, 1]])

In [11]:
tensor_3 = torch.ones_like(data_tensor, dtype=torch.float16) # j.w. z wartościami typu float16
tensor_3

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float16)

In [12]:
tensor_4 = torch.clone(tensor_3) # kopia tensora tensor_3
tensor_4

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float16)

W ostatnim przypadku warto zajrzeć do dokumentacji metody [torch.clone](https://pytorch.org/docs/stable/generated/torch.clone.html) oraz [detach](https://pytorch.org/docs/stable/autograd.html#torch.Tensor.detach).

### Z wartościami losowymi bądź stałymi
Zmienna **tensor_shape** jest krotką, reprezentującą wymiary tensora. W poniższych funkcjach jest przekazywana jako argument, określający wymiar tworzonego tensora.

In [13]:
tensor_shape = (2,3,2) # interpretacja: dwie macierze o wymiarze 3x2
tensor_random = torch.rand(tensor_shape) # tensor o losowych wartościach z rozkładu jednorodnego
tensor_random

tensor([[[0.0973, 0.0194],
         [0.0615, 0.3059],
         [0.7734, 0.0304]],

        [[0.5501, 0.4841],
         [0.5691, 0.1861],
         [0.8892, 0.2019]]])

In [14]:
tensor_ones = torch.ones(tensor_shape) # tensor o wartościach równych 1
tensor_ones

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [15]:
tensor_zeros = torch.zeros(tensor_shape) # tensor o wartościach równych 0
tensor_zeros

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

---
**ZADANIE 2**

Utwórz kształt **my_shape_2**, a na jego podstawie taki tensor **my_tensor_2** o wartościach losowych, by kształt macierzy wyjściowej był taki jak podanej poniżej:

$\begin{bmatrix}
0 & 0\\
0 & 0\\
0 & 0\\
\end{bmatrix}$

In [16]:
my_shape_2 = (1, 3, 2)
my_tensor_2 = torch.rand(my_shape_2)
my_tensor_2

tensor([[[0.8274, 0.8542],
         [0.1950, 0.5914],
         [0.7466, 0.6507]]])

---
## Atrybuty tensora
Atrybuty tensora opisują jego kształt, typ danych oraz urządzenie, na którym tensor jest przechowywany.

In [17]:
tensor_random.shape # kształt

torch.Size([2, 3, 2])

In [18]:
tensor_random.dtype # typ danych

torch.float32

In [19]:
tensor_random.device # urządzenie

device(type='cpu')

Tensor można przenieść do karty graficznej (GPU) lub innego urządzenia wspierającego operacje [CUDA](https://pl.wikipedia.org/wiki/CUDA) \(np. [TPU](https://en.wikipedia.org/wiki/Tensor_Processing_Unit)\), o ile jest dostępne.

In [20]:
if torch.cuda.is_available(): # metoda sprawdzająca dostępność urządzenia CUDA (GPU lub TPU)
  tensor_cuda = tensor_random.to('cuda') # metoda przenosi tensor na wybrane urządzenie


In [21]:
tensor_cuda

tensor([[[0.0973, 0.0194],
         [0.0615, 0.3059],
         [0.7734, 0.0304]],

        [[0.5501, 0.4841],
         [0.5691, 0.1861],
         [0.8892, 0.2019]]], device='cuda:0')

---
**ZADANIE 3**

Przenieś na GPU tensory z zadania 1 i 2.

In [22]:
if torch.cuda.is_available():
  my_tensor_cuda = my_tensor.to('cuda')
  my_tensor_2_cuda = my_tensor_2.to('cuda')

my_tensor_cuda

tensor([[2, 4, 6],
        [1, 3, 5]], device='cuda:0')

In [23]:
my_tensor_2_cuda

tensor([[[0.8274, 0.8542],
         [0.1950, 0.5914],
         [0.7466, 0.6507]]], device='cuda:0')

---
# Operacje na tensorach
Wiele operacji na tensorach w PyTorch jest bardzo podobnych do operacji w NumPy. Niektóre przykłady będą zawierały analogie przedstawione na tablicach NumPy.

### Indeksowanie
Najpierw utworzone zostaną dwie zmienne: **tensor** przechowująca tensor o wymiarach 3x4 oraz **array** będącą tablicą NumPy utworzoną na podstawie **tensor**.

In [24]:
tensor = torch.zeros(3,4)
array = tensor.numpy()
print(tensor)
print(array)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Modyfikacja elementu o podanym indeksie
Indeksy działają analogicznie jak w przypadku [tablic NumPy](https://numpy.org/doc/stable/reference/arrays.indexing.html).

In [25]:
tensor[1,2] = 1
array[1,2] = 1
print(tensor)
print(array)

tensor([[0., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 0.]])
[[0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]


### Wydzielenie fragmentu tensora/tablicy


In [26]:
tensor[:,2:]

tensor([[0., 0.],
        [1., 0.],
        [0., 0.]])

In [27]:
array[1:3,1:4]

array([[0., 1., 0.],
       [0., 0., 0.]], dtype=float32)

### Łączenie tensorów


In [28]:
t1 = torch.zeros(3,2)
t2 = torch.ones(3,1)
t3 = torch.cat([t1, t2, t1], dim=1)
t3

tensor([[0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.]])

---
**ZADANIE 4**

Zdefiniuj w postaci tensorów macierze A i B:

$A = \begin{bmatrix}
0 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 1 & 2\\
0 & 0 & 0 & 1 & 2\\
0 & 0 & 0 & 1 & 2\\
0 & 0 & 0 & 0 & 0\\
\end{bmatrix}$

$B = \begin{bmatrix}
0 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0\\
0 & 0 & 3 & 4 & 0\\
0 & 0 & 3 & 4 & 0\\
0 & 0 & 3 & 4 & 0\\
\end{bmatrix}$

Wykorzystując poznane operacje tensorowe na macierzach A i B, utwórz tensor C, reprezentujący następującą macierz:
$C = \begin{bmatrix}
1 & 2 & 3 & 4\\
1 & 2 & 3 & 4\\
1 & 2 & 3 & 4\\
\end{bmatrix}$


In [29]:
A = torch.tensor([
    [0, 0, 0, 0, 0],
    [0, 0, 0, 1, 2],
    [0, 0, 0, 1, 2],
    [0, 0, 0, 1, 2],
    [0, 0, 0, 0, 0]
])

B = torch.tensor([
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 3, 4, 0],
    [0, 0, 3, 4, 0],
    [0, 0, 3, 4, 0]
])

blok_A = A[1:4, 3:]
blok_B = B[2:5, 2:4]

C = torch.cat([blok_A, blok_B], dim=1)
C

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]])

---
### Mnożenie tensorów



In [30]:
# zdefiniowanie 3 przykładowych tensorów
t1 = torch.tensor([[1,2],[3,4],[2,3]])
t2 = torch.tensor([[2,5],[3,6],[4,7]])
t3 = torch.tensor([[2,3]])

# mnożenie dwóch tensorów (Uwaga! To nie jest mnożenie macierzowe znane z algebry!)
t4 = t1.mul(t2)
t5 = t1.mul(t3)

# mnożenie macierzy przez liczbę
t6 = t1.mul(5)
print(t1)
print(t2)
print(t3)
print(t4)
print(t5)
print(t6)

tensor([[1, 2],
        [3, 4],
        [2, 3]])
tensor([[2, 5],
        [3, 6],
        [4, 7]])
tensor([[2, 3]])
tensor([[ 2, 10],
        [ 9, 24],
        [ 8, 21]])
tensor([[ 2,  6],
        [ 6, 12],
        [ 4,  9]])
tensor([[ 5, 10],
        [15, 20],
        [10, 15]])


In [31]:
# alternatywnie dla powyższych operatorów, można zapisać:
t4 = t1 * t2
t5 = t1 * t3
t6 = t1 * 5
print(t4)
print(t5)
print(t6)

tensor([[ 2, 10],
        [ 9, 24],
        [ 8, 21]])
tensor([[ 2,  6],
        [ 6, 12],
        [ 4,  9]])
tensor([[ 5, 10],
        [15, 20],
        [10, 15]])


In [32]:
# transpozycja macierzy
print(t1)
print(t1.T)


tensor([[1, 2],
        [3, 4],
        [2, 3]])
tensor([[1, 3, 2],
        [2, 4, 3]])


---
**ZADANIE 5**

Zdefiniuj t3 jako tensor [[2,3,4]] i powtórz powyższe operacje korzystające z t3. Co możesz zrobić z tensorem t3, żeby operacje wykonały się prawidłowo? Co się stanie, jeśli przeniesiesz wyłącznie t3 na GPU i powtórzysz operacje, które wykonywały się prawidłowo?


In [35]:
t3 = torch.tensor([[2, 3, 4]])
t5 = t1.mul(t3)

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

---
### Mnożenie macierzowe

In [36]:
# Mnożenie macierzowe wykonywane jest w następujący sposób:
print('t1: ', t1)
print(t2)
print(t2.T)
print(t1.matmul(t2.T))

t1:  tensor([[1, 2],
        [3, 4],
        [2, 3]])
tensor([[2, 5],
        [3, 6],
        [4, 7]])
tensor([[2, 3, 4],
        [5, 6, 7]])
tensor([[12, 15, 18],
        [26, 33, 40],
        [19, 24, 29]])


In [37]:
# Zapis alternatywny:
print(t1 @ t2.T)

tensor([[12, 15, 18],
        [26, 33, 40],
        [19, 24, 29]])


### Operacje "w miejscu" (in-place)

In [38]:
# Uwaga! Operacje w miejscu pomagają oszczędzić pamięć, ale mogą nadpisać wartości potrzebne do wyznaczania gradientu.
# Więcej informacji można znaleźć tu: https://pytorch.org/docs/stable/notes/autograd.html#in-place-operations-with-autograd

# Operacje w miejscu są zdefiniowane z sufiksem "_"
print(t1)
t1.add_(5)
print(t1)
t1.mul_(2)
print(t1)

tensor([[1, 2],
        [3, 4],
        [2, 3]])
tensor([[6, 7],
        [8, 9],
        [7, 8]])
tensor([[12, 14],
        [16, 18],
        [14, 16]])


### Pełna lista operacji tensorowych

Z pełną listą operacji tensorowych można zapoznać się tutaj:

https://pytorch.org/docs/stable/torch.html#

---
**ZADANIE 6**

Na podstawie [dokumentacji PyTorch](https://pytorch.org/docs/stable/torch.html#) znajdź operator, przy pomocy którego zrealizujesz następujące przekształcenia:

A.
$\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{bmatrix} \rightarrow
\begin{bmatrix}
1 & 0 & 3 \\
0 & 5 & 0 \\
7 & 0 & 9 \\
\end{bmatrix}
$

B.
$\begin{bmatrix}
2 & 5 & 8 & 3 & 1\\
9 & 2 & 4 & 5 & 8\\
4 & 7 & 1 & 2 & 3\\
2 & 7 & 3 & 6 & 8\\
1 & 5 & 6 & 9 & 2\\
\end{bmatrix} \rightarrow
\begin{bmatrix}
2 & 0 & 1 & 4 & 3\\
\end{bmatrix}
$

C.
$\begin{bmatrix}
2 & 5 & 8 & 3 & 1\\
9 & 2 & 4 & 5 & 8\\
4 & 7 & 1 & 2 & 3\\
2 & 7 & 3 & 6 & 8\\
1 & 5 & 6 & 9 & 2\\
\end{bmatrix} \rightarrow
\begin{bmatrix}
8 & 9 & 7 & 8 & 9\\
\end{bmatrix}
$

D.
$\begin{bmatrix}
2 & 5 & 8 & 3 & 1\\
9 & 2 & 4 & 5 & 8\\
4 & 7 & 1 & 2 & 3\\
2 & 7 & 3 & 6 & 8\\
1 & 5 & 6 & 9 & 2\\
\end{bmatrix} \rightarrow
\begin{bmatrix}
18 & 26 & 22 & 25 & 22\\
\end{bmatrix}
$

E.
$\begin{bmatrix}
2 & 5 & 8 & 3 & 1\\
9 & 2 & 4 & 5 & 8\\
4 & 7 & 1 & 2 & 3\\
2 & 7 & 3 & 6 & 8\\
1 & 5 & 6 & 9 & 2\\
\end{bmatrix} \rightarrow
\begin{bmatrix}
1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9\\
\end{bmatrix}
$

F.
$\begin{bmatrix}
2 & 5 & 8 & 3 & 1\\
9 & 2 & 4 & 5 & 8\\
4 & 7 & 1 & 2 & 3\\
2 & 7 & 3 & 6 & 8\\
1 & 5 & 6 & 9 & 2\\
\end{bmatrix} \rightarrow
\begin{bmatrix}
False & True & True & False & False\\
True & False & False & True & True\\
False & True & False & False & False\\
False & True & False & True & True\\
False & True & True & True & False\\
\end{bmatrix}$

G.
$\begin{bmatrix}
2 & 5 & 8 & 3 & 1\\
9 & 2 & 4 & 5 & 8\\
4 & 7 & 1 & 2 & 3\\
2 & 7 & 3 & 6 & 8\\
1 & 5 & 6 & 9 & 2\\
\end{bmatrix} \rightarrow
\begin{bmatrix}
8 & 5 & 3 & 2 & 1\\
9 & 8 & 5 & 4 & 2\\
7 & 4 & 3 & 2 & 1\\
8 & 7 & 6 & 3 & 2\\
9 & 6 & 5 & 2 & 1\\
\end{bmatrix},
\begin{bmatrix}
2 & 1 & 3 & 0 & 4\\
0 & 4 & 3 & 2 & 1\\
1 & 0 & 4 & 3 & 2\\
4 & 1 & 3 & 2 & 0\\
3 & 2 & 1 & 4 & 0\\
\end{bmatrix}$

H.
$\begin{bmatrix}
2 & 5 & 8 & 3 & 1\\
9 & 2 & 4 & 5 & 8\\
4 & 7 & 1 & 2 & 3\\
2 & 7 & 3 & 6 & 8\\
1 & 5 & 6 & 9 & 2\\
\end{bmatrix} \rightarrow
\begin{bmatrix}
8 & 5 \\
9 & 8 \\
7 & 4 \\
8 & 7 \\
9 & 6 \\
\end{bmatrix},
\begin{bmatrix}
2 & 1 \\
0 & 4 \\
1 & 0 \\
4 & 1 \\
3 & 2 \\
\end{bmatrix}$

I.
$\begin{bmatrix}
2 & 5 & 8 & 3 & 1\\
9 & 2 & 4 & 5 & 8\\
4 & 7 & 1 & 2 & 3\\
2 & 7 & 3 & 6 & 8\\
1 & 5 & 6 & 9 & 2\\
\end{bmatrix} \rightarrow
\begin{bmatrix}
2 & 7 & 15 & 18 & 19\\
9 & 11 & 15 & 20 & 28\\
4 & 11 & 12 & 14 & 17\\
2 & 9 & 12 & 18 & 26\\
1 & 6 & 12 & 21 & 23\\
\end{bmatrix}$

J.
$\begin{bmatrix}
1 & 2 \\
2 & 3 \\
3 & 4 \\
\end{bmatrix} \rightarrow
\begin{bmatrix}
1 & 2 & 2 & 3 & 3 & 4 \\
\end{bmatrix}
$

K.
$\begin{bmatrix}
2 & 5 & 8 & 3 & 1\\
9 & 2 & 4 & 5 & 8\\
4 & 7 & 1 & 2 & 3\\
2 & 7 & 3 & 6 & 8\\
1 & 5 & 6 & 9 & 2\\
\end{bmatrix} \rightarrow
\begin{bmatrix}
1 & 3 & 8 & 5 & 2\\
8 & 5 & 4 & 2 & 9\\
3 & 2 & 1 & 7 & 4\\
8 & 6 & 3 & 7 & 2\\
2 & 9 & 6 & 5 & 1\\
\end{bmatrix}$


In [58]:
#A.
A = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
mask = torch.tensor([[1,0,1],
                     [0,1,0],
                     [1,0,1]])
result_A = A * mask  # lub torch.mul(A, mask)
print(result_A)

#B.
B = torch.tensor([[2,5,8,3,1],
                  [9,2,4,5,8],
                  [4,7,1,2,3],
                  [2,7,3,6,8],
                  [1,5,6,9,2]])
# Przyjmijmy, że dla każdej kolumny chcemy wybrać element z określonego wiersza.
# Indeksy (o kształcie [1, 5]) określą, z którego wiersza pobrać wartość dla danej kolumny.
#indices = torch.tensor([[0, -1, 2, 1, 0]])  # przykład – należy dobrać tak, by wynik był [2,0,1,4,3]
indices = torch.tensor([[0, 1, 2, 1, 2]])
# Jeśli chcemy w niektórych kolumnach uzyskać 0, możemy najpierw stworzyć maskę lub dokonać operacji warunkowej.
result_B = B.gather(dim=0, index=indices)  # operator torch.gather
print(result_B)

#C.
# Dla każdej z 5 wierszy pobieramy maksimum
max_values, _ = B.max(dim=1)
result_C = max_values  # tensor kształtu (5,)
print(result_C)

#D.
print(B.sum(dim=0))

#E.
print(B.unique(sorted=True))

#F.
print(B > 4)

#G.
print("G.", B.sort(descending=True, dim=1))

#H.
print("H.", B.topk(k=2, dim=1))

#I.
print("I.", B.cumsum(dim=1))

#J.
print("J.", B.flatten())

#K.
print("K", B.flip(dims=[1]))


tensor([[1, 0, 3],
        [0, 5, 0],
        [7, 0, 9]])
tensor([[2, 2, 1, 5, 3]])
tensor([8, 9, 7, 8, 9])
tensor([18, 26, 22, 25, 22])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[False,  True,  True, False, False],
        [ True, False, False,  True,  True],
        [False,  True, False, False, False],
        [False,  True, False,  True,  True],
        [False,  True,  True,  True, False]])
G. torch.return_types.sort(
values=tensor([[8, 5, 3, 2, 1],
        [9, 8, 5, 4, 2],
        [7, 4, 3, 2, 1],
        [8, 7, 6, 3, 2],
        [9, 6, 5, 2, 1]]),
indices=tensor([[2, 1, 3, 0, 4],
        [0, 4, 3, 2, 1],
        [1, 0, 4, 3, 2],
        [4, 1, 3, 2, 0],
        [3, 2, 1, 4, 0]]))
H. torch.return_types.topk(
values=tensor([[8, 5],
        [9, 8],
        [7, 4],
        [8, 7],
        [9, 6]]),
indices=tensor([[2, 1],
        [0, 4],
        [1, 0],
        [4, 1],
        [3, 2]]))
I. tensor([[ 2,  7, 15, 18, 19],
        [ 9, 11, 15, 20, 28],
        [ 4, 11, 12, 14, 17],
    

<a name="homework"></a>
# Zadanie domowe

W ramach zadania domowego należy przygotować środowisko uruchomieniowe dla PyTorch. W tym celu należy zainstalować następujące elementy:


*   [Python (wersja 3.x)](https://www.python.org/)
*   [Sterowniki NVIDIA](https://www.nvidia.com/Download/index.aspx)
*   [CUDA Toolkit 9.2-11.0](https://developer.nvidia.com/cuda-zone)
*   [PyTorch 1.7.1](https://pytorch.org/)

Dla osób nieposiadających GPU zalecane jest korzystanie z Google Colab.

Przydatne instrukcje dla następujących systemów:


*   [Ubuntu 20.04](https://varhowto.com/install-pytorch-ubuntu-20-04/)
*   [Windows 10](https://pub.towardsai.net/installing-pytorch-with-cuda-support-on-windows-10-a38b1134535e)



